admin_user: ubuntu
admin_ssh_pubkey: "{{ lookup('file', '~/.ssh/vps1_ovh.pub') }}"
swap_size_mb: 2048
swappiness: 40

k3s_version: v1.35.8+k3s1
cilium_version: 1.20.0
helm_version: "3.22.0"
k8s_pod_cidr: 10.42.0.0/16
k8s_service_cidr: 10.43.0.0/16
k8s_api_host: "{{ ansible_facts['default_ipv4']['address'] }}"

app_namespace: kuby
github_user: MagnanJules
deploy_ssh_pubkey_path: ~/.config/kube-lab/deploy_key.pub
gateway_api_key: "{{ vault_gateway_api_key }}"
ghcr_pull_token: "{{ vault_ghcr_pull_token | default('') }}"

public_host: "{{ ansible_default_ipv4.address }}"
public_domain: julesmagnan.com

fleet_repo: fleet
cluster_name: vps1
github_bootstrap_token: "{{ vault_github_bootstrap_token }}"
sops_age_key: "{{ vault_sops_age_key }}"

rate_limited_ports: "80,443"
rate_limit_new_connections: 60/minute
rate_limit_burst: 100
rate_limit_concurrent: 50
