- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Limit connexion by IPs
  ansible.builtin.blockinfile:
    path: "{{ item.path }}"
    marker: "# {mark} ANSIBLE rate limit"
    insertbefore: "^COMMIT"
    block: |
      -A {{ item.chain }} -p tcp -m multiport --dports {{ rate_limited_ports }} -m conntrack --ctstate NEW -m hashlimit --hashlimit-name {{ item.name }} --hashlimit-mode srcip --hashlimit-srcmask {{ item.mask }} --hashlimit-above {{ rate_limit_new_connections }} --hashlimit-burst {{ rate_limit_burst }} -j DROP
      -A {{ item.chain }} -p tcp --syn -m multiport --dports {{ rate_limited_ports }} -m connlimit --connlimit-above {{ rate_limit_concurrent }} --connlimit-mask {{ item.mask }} -j REJECT --reject-with tcp-reset
  loop:
    - { path: /etc/ufw/before.rules, chain: ufw-before-input, name: ratelimit4, mask: 32 }
    - { path: /etc/ufw/before6.rules, chain: ufw6-before-input, name: ratelimit6, mask: 64 }
  notify: reload ufw

- name: Allowing SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow traffic from pods/services to host
  community.general.ufw:
    rule: allow
    from_ip: "{{ item }}"
  loop:
    - "{{ k8s_pod_cidr }}"
    - "{{ k8s_service_cidr }}"

- name: Default incoming policy
  community.general.ufw:
    default: deny
    direction: incoming

- name: Default outgoing policy
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Allowing firewall
  community.general.ufw:
    state: enabled

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow HTTPs
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp


